pipelines:
  - name: first
    steps:
      - name: step1
        type: Bash
        configuration:
          integrations:
            - name: gits
          nodePool: oneboxMacOS13
          runtime:
            type: host
        execution:
          onExecute:
            - echo "Hello World"
